# Generated by Django 3.2.7 on 2021-09-12 18:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='container name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('identifier', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='identifier')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='location name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Optionally. Longitude as decimal up-to 6 decimals.', max_digits=9, null=True, verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Optionally. Latitude as decimal up-to 6 decimals.', max_digits=9, null=True, verbose_name='latitude')),
                ('identifier', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='ims.identifier', verbose_name='identifier')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='ims.locationtype', verbose_name='location type')),
                ('parent_location', models.ForeignKey(blank=True, help_text='locations can be marked as sub-locations by providing a parent locations here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_locations', to='ims.location', verbose_name='parent location')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='item name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ims.container', verbose_name='container')),
                ('identifier', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='ims.identifier', verbose_name='identifier')),
                ('location', models.ForeignKey(blank=True, help_text='if item is linked to a container with a location, there is no need to explicitly assign the item a location as it is inherited.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ims.location', verbose_name='location')),
                ('tags', models.ManyToManyField(blank=True, help_text='optionally add tags for easy sorting/searching etc.', related_name='items', to='ims.Tag', verbose_name='tags')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='ims.containertype', verbose_name='container type'),
        ),
        migrations.AddField(
            model_name='container',
            name='identifier',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='ims.identifier', verbose_name='identifier'),
        ),
    ]
