# Generated by Django 3.2.7 on 2021-09-24 17:42

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_alter_location_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=martor.models.MartorField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=martor.models.MartorField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=martor.models.MartorField(blank=True, verbose_name='description'),
        ),
    ]
