# Generated by Django 3.2.7 on 2021-09-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_alter_desc_to_martor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='identifier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='ims.identifier', verbose_name='identifier'),
        ),
    ]
